// Headless checks for the application's own local preview.
const { chromium } = require(process.env.NEXTONE_PLAYWRIGHT || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:4173/');
  await page.getByRole('heading', { name: 'Hola, Camilo.' }).waitFor();
  await page.evaluate(() => document.fonts.ready);
  fs.mkdirSync('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Crear proyecto', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nombre del proyecto').fill('Automatización para equipos');
  await dialog.getByLabel('Problema y solución').fill('Crear una herramienta de automatización que ayude a equipos pequeños a organizar sus tareas y documentar avances de forma consistente.');
  await dialog.getByLabel('Alcance y entregable').fill('Una aplicación web con tablero de tareas y bitácora del equipo.');
  await dialog.getByLabel('Factor diferenciador').fill('Diseñada para equipos de aprendizaje con revisiones entre pares.');
  await dialog.getByLabel('Tecnologías').fill('React, TypeScript');
  await dialog.getByLabel('Roles necesarios').fill('Frontend, Backend');
  await dialog.getByRole('button', { name: 'Revisar propuesta demo' }).click();
  await dialog.getByText('Descripción lista para crear un borrador').waitFor();
  await dialog.getByRole('button', { name: 'Crear proyecto demo' }).click();
  await page.getByRole('heading', { name: 'Automatización para equipos', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Tareas', exact: true }).click();
  await page.getByRole('button', { name: 'Nueva tarea' }).click();
  await page.getByLabel('Qué debemos hacer').fill('Validar el flujo inicial');
  await page.getByRole('button', { name: 'Guardar', exact: true }).click();
  await page.getByRole('heading', { name: 'Validar el flujo inicial' }).waitFor();
  await page.getByRole('button', { name: 'Cambiar estado' }).click();
  await page.getByRole('button', { name: 'Conversaciones', exact: true }).click();
  await page.getByRole('textbox', { name: 'Mensaje', exact: true }).fill('Primer avance registrado desde el navegador.');
  await page.getByRole('button', { name: 'Enviar', exact: true }).click();
  await page.getByText('Primer avance registrado desde el navegador.', { exact: true }).waitFor();
  await page.reload();
  await page.getByRole('button', { name: /Proyectos/ }).first().click();
  await page.getByRole('button', { name: /Automatización para equipos/ }).click();
  await page.getByRole('button', { name: 'Tareas', exact: true }).click();
  await page.getByRole('heading', { name: 'Validar el flujo inicial' }).waitFor();
  await page.getByRole('combobox', { name: 'Explorar como' }).selectOption('visitor');
  await page.getByRole('button', { name: 'Solicitar ingreso', exact: true }).click();
  await page.getByLabel('Nombre completo').fill('Test Builder');
  await page.getByLabel('Correo').fill('builder@example.com');
  await page.getByLabel('Habilidades técnicas').fill('React, TypeScript');
  await page.getByLabel('Portafolio o GitHub').fill('https://example.com/portfolio');
  await page.getByLabel('LinkedIn').fill('https://example.com/linkedin');
  await page.getByLabel('Qué te gustaría aportar').fill('Colaborar en proyectos de desarrollo web.');
  await page.getByLabel('Código de invitación').fill('mentor-demo');
  await page.getByRole('button', { name: 'Enviar solicitud demo' }).click();
  await page.getByRole('heading', { name: /Ingreso directo aprobado/ }).waitFor();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('heading', { name: 'Hola, Test.' }).waitFor();
  await page.getByRole('button', { name: /Proyectos/ }).first().click();
  await page.getByRole('button', { name: /Automatización para equipos/ }).click();
  assert.equal(await page.getByRole('button', { name: 'Documentación', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Solicitar unirme', exact: true }).click();
  await page.getByRole('combobox', { name: 'Explorar como' }).selectOption('you');
  await page.getByRole('button', { name: /Proyectos/ }).first().click();
  await page.getByRole('button', { name: /Automatización para equipos/ }).click();
  await page.getByRole('button', { name: /Equipo/ }).click();
  await page.getByRole('button', { name: 'Aprobar', exact: true }).click();
  const memberId = await page.evaluate(() => JSON.parse(localStorage.getItem('nextone.demo.v1')).people.find(p => p.name === 'Test Builder').id);
  await page.getByRole('combobox', { name: 'Explorar como' }).selectOption(memberId);
  await page.getByRole('button', { name: /Proyectos/ }).first().click();
  await page.getByRole('button', { name: /Automatización para equipos/ }).click();
  await page.getByRole('button', { name: 'Documentación', exact: true }).click();
  await page.getByText('Solo lectura', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Salir del equipo', exact: true }).click();
  await page.getByLabel('Motivo de salida').fill('Prueba de salida voluntaria con motivo.');
  await page.getByRole('button', { name: 'Guardar', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Documentación', exact: true }).count(), 0);
  await page.getByRole('combobox', { name: 'Explorar como' }).selectOption('you');
  await page.getByRole('button', { name: 'Cambiar a inglés' }).click();
  await page.getByRole('heading', { name: 'Hello, Camilo.' }).waitFor();
  await page.getByRole('button', { name: 'Switch theme' }).click();
  await page.getByRole('button', { name: 'Close', exact: true }).click().catch(() => {});
  await page.screenshot({ path: 'artifacts/light-en.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.waitForTimeout(350); // Let the sidebar's responsive transition settle.
  await page.getByRole('button', { name: 'Open menu' }).click();
  await page.getByRole('button', { name: /Learning/ }).click();
  await page.getByRole('heading', { name: 'Grow with every project.' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.getByRole('heading', { name: 'Hola, Camilo.' }).waitFor();
  await page.waitForTimeout(350);
  await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  console.log('Browser checks passed: creation, assistant, tasks, chat, persistence, direct admission, leader approval, read-only documentation, exit, language, theme and mobile navigation.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
